### ISSUE TITLE
构建4.3.0 all-in-one时出错

### ISSUE THREAD

**Issue by meilihao** [zstackio/zstack-utility#393]
log:
```bash
$ cd zstack-repos && tree -L 1 .
.
├── apache-tomcat-8.5.57.zip
├── zstack
├── zstack-utility
└── zstack-vyos
$ cd zstack-utility/zstackbuild
$ ant -propertyfile build.oss.properties     -buildfile build.oss.xml     -Dzstack_build_root=/home/chen/mark/test/zstack-repos     -Dbuild.zstack.ui.war=false     all-in-one -v
....
build-zstack-dashboard:
     [echo] rm -rf /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/target/zstackdashboard
     [exec] /home/chen/mark/test/zstack-repos/zstack-utility/cephprimarystorage/setup.py
     [exec] Current OS is Linux
     [exec] Executing 'rm' with arguments:
     [exec] '-rf'
     [exec] '/opt/mark/test/zstack-repos/zstack-utility/zstackbuild/target/zstackdashboard'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] /home/chen/mark/test/zstack-repos/zstack-utility/consoleproxy/zstack-consoleproxy
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] /home/chen/mark/test/zstack-repos/zstack-utility/sftpbackupstorage/zstack-sftpbackupstorage
     [echo] checking if file[/home/chen/mark/test/zstack-repos/zstack-utility/cephprimarystorage/zstack-ceph-primarystorage] exists ...
     [exec] Current OS is Linux
     [exec] Executing 'ls' with arguments:
     [exec] '/home/chen/mark/test/zstack-repos/zstack-utility/cephprimarystorage/zstack-ceph-primarystorage'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] /home/chen/mark/test/zstack-repos/zstack-utility/cephprimarystorage/zstack-ceph-primarystorage
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] Current OS is Linux
     [exec] Executing 'python' with arguments:
     [exec] 'setup.py'
     [exec] 'sdist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
    [mkdir] Created dir: /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/target/zstackdashboard
     [echo] checking if file[/home/chen/mark/test/zstack-repos/zstack-dashboard] exists ...
     [exec] Current OS is Linux
     [exec] Executing 'ls' with arguments:
     [exec] '/home/chen/mark/test/zstack-repos/zstack-dashboard'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] ls: 无法访问 '/home/chen/mark/test/zstack-repos/zstack-dashboard': 没有那个文件或目录
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.

BUILD FAILED
/opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml:300: The following error occurred while executing this line:
/opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml:268: The following error occurred while executing this line:
/opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml:216: The following error occurred while executing this line:
/opt/mark/test/zstack-repos/zstack-utility/zstackbuild/projects/zstack-dashboard.xml:16: The following error occurred while executing this line:
/opt/mark/test/zstack-repos/zstack-utility/zstackbuild/utils.xml:8: exec returned: 2
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:645)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:497)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.util.Vector.forEach(Vector.java:1277)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.util.Vector.forEach(Vector.java:1277)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:454)
	at java.lang.Thread.run(Thread.java:748)

Total time: 16 minutes 58 seconds
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.
  [antcall] Exiting /opt/mark/test/zstack-repos/zstack-utility/zstackbuild/build.oss.xml.
```

**Comment by meilihao** [comment]
今天偶然发现gitee有更新的zstack版本，测试了4.3.28，同样因为zstack-dashboard没有而报错.
